/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.REGION,
    "aws_cognito_region": process.env.COGNITO_REGION,
    "aws_user_pools_id": process.env.COGNITO_USERPOOL_ID,
    "aws_user_pools_web_client_id": process.env.COGNITO_USERPOOL_CLIENT_ID,
};

export default awsmobile
